### ISSUE TITLE
[BUG] The example vrep_interface_move_kuka_and_youtubot.cpp is not working

### ISSUE THREAD

**Issue by juanjqo** [dqrobotics/cpp-examples#10]
Hi @dqrobotics/developers!

**Bug description**
- The example `cmake/vrep_interface/vrep_interface_move_kuka_and_youtbot.cpp` is not working properly. The example code crashes when I try to run it.

**To Reproduce**
From cpp-examples (master): Build and run `vrep_interface/vrep_interface_move_kuka_and_youtbot.cpp`

*Code*
From cpp-examples (master):

```CPP
  cmake/vrep_interface/vrep_interface_move_kuka_and_youtbot.cpp
```
*Output*
```
Starting V-REP simulation...
There was an error connecting to V-REP, please check that it is open and that the Kuka Robot is in the scene.
Tried to access chain index 7 which is unnavailable.
```

**Expected behavior**
- The example must run succesfully using the [vrep_scene_felt_pen_official_scene.ttt](https://github.com/dqrobotics/matlab-examples/blob/master/vrep/simulation-ram-paper/vrep_scene_felt_pen_official_scene.ttt) 

**Environment:**
 - OS: Ubuntu 20.04.4 LTS
 - dqrobotics version: 
       C++ (development branch) (20.04.0-0-202206300608-ubuntu20.04.1)

**Comment by mmmarinho** [comment]
@juanjqo  Try the new version.

Notice that I moved away from CPLEX so please install [qpOASES](https://github.com/dqrobotics/cpp-interface-qpoases).

**Comment by juanjqo** [comment]
@mmmarinho The example (vrep_interface_move_kuka.cpp) is not compiling. It is required adding the line
```CPP
#include <dqrobotics/robot_modeling/DQ_SerialWholeBody.h>
```
 in the source code and adding pthread in the CMake:

```CMAKE
TARGET_LINK_LIBRARIES(vrep_interface_move_kuka_and_youbot
    pthread
    dqrobotics
    dqrobotics-interface-vrep
    qpOASES
)
```

However, the class YouBotVrepRobot (from dqrobotics/cpp-interface-vrep) is still using (in my local files) DQ_WholeBody instead of DQ_SerialWholeBody. Maybe I have to wait to get the last update available in the PPA?

**Comment by mmmarinho** [comment]
@juanjqo Either wait for the PPA to update  (could take around 24 hours) or compile and install the .deb.

**Comment by mmmarinho** [comment]
@juanjqo 

This could conflict with the PPA so you'd have to remove it first (and all related packages).

Just FYI
```bash
cd ~
git clone https://github.com/dqrobotics/cpp.git
cd cpp
./.github/scripts/ubuntu/build.sh
sudo ./.github/scripts/ubuntu/install.sh
```
