### ISSUE TITLE
[BUG] The example qpoases_interface.cpp does not compile

### ISSUE THREAD

**Issue by juanjqo** [dqrobotics/cpp-examples#11]
**Bug description**
- By following the _official_ instructions, the example qpoases_interface.cpp but fails to compile.  

By official instructions I mean the following steps:

- Install the [qpOASES library](https://github.com/dqrobotics/cpp-interface-qpoases)
These procedures install the qpOASES library as a share library in `/usr/local/include`

- Install the DQ robotics interface 

`sudo apt-get install libdqrobotics-interface-qpoases`

Despite that, the example qpoases_interface.cpp fails to compile because the DQ robotics interface does not find the qpOASES shared library. 

 A solution is to move the library (a qpOASES folder and a qpOASES.hpp file) from `/usr/local/include` to `/usr/include`. In this way, the  DQ robortics-interface finds the shared library successfully, and therefore, the example compiles. 

**To Reproduce**

*Code*

```
cpp-examples (master-branch): cmake/qp_oases_interface/qpoases_interface.cpp
```
*Output*
```
14:22:05: Running steps for project qpoases_interface...
14:22:05: Starting: "/home/juanjqo/Qt/Tools/CMake/bin/cmake" --build /home/juanjqo/Documents/My_repositories/cpp-examples/cmake/build-qpoases_interface-Desktop_Qt_6_3_1_GCC_64bit-Debug --target all
[1/2 14.0/sec] Building CXX object CMakeFiles/qpoases_interface.dir/qpoases_interface.cpp.o
FAILED: CMakeFiles/qpoases_interface.dir/qpoases_interface.cpp.o 
/home/linuxbrew/.linuxbrew/bin/g++-11   -g -std=gnu++11 -MD -MT CMakeFiles/qpoases_interface.dir/qpoases_interface.cpp.o -MF CMakeFiles/qpoases_interface.dir/qpoases_interface.cpp.o.d -o CMakeFiles/qpoases_interface.dir/qpoases_interface.cpp.o -c /home/juanjqo/Documents/My_repositories/cpp-examples/cmake/qpoases_interface/qpoases_interface.cpp
In file included from /home/juanjqo/Documents/My_repositories/cpp-examples/cmake/qpoases_interface/qpoases_interface.cpp:27:
/usr/include/dqrobotics/solvers/DQ_QPOASESSolver.h:31:10: fatal error: qpOASES.hpp: No such file or directory
   31 | #include <qpOASES.hpp>
      |          ^~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
14:22:05: The process "/home/juanjqo/Qt/Tools/CMake/bin/cmake" exited with code 1.
Error while building/deploying project qpoases_interface (kit: Desktop Qt 6.3.1 GCC 64bit)
When executing step "Build"
14:22:05: Elapsed time: 00:00.
```

**Expected behavior**
- A successful build and execution.

*Expected output*
```
q_dot is  -0.00311208   0.00617398   0.00304193   -0.0015048   0.00304193 -0.000791966   0.00304193
```

**Environment:**
 - OS: [Ubuntu 20.04 LTS]
 - dqrobotics version
C++ (development-branch) 20.04.0-0-202206300608-ubuntu20.04.1.

**Comment by mmmarinho** [comment]
@juanjqo Don’t move anything manually.

After you install any library you have to run 
‘sudo ldconfig’ 
If you want it to be recognized in that same terminal. 

Please remove whatever you changed and try again from the beginning.

**Comment by juanjqo** [comment]
@mmmarinho I did that step. 
I'm going to remove the files to try again.

**Comment by mmmarinho** [comment]
@juanjqo  you can see it working in GithubActions.

https://github.com/dqrobotics/cpp-interface-qpoases/runs/7124654957?check_suite_focus=true

Please check if that workflow is doing anything different from what is described in the README, if so we can update the instructions for installing qpOASES.

**Comment by juanjqo** [comment]
@mmmarinho 

The example compiles using the terminal only. Do you have any tips to compile the example in Qt creator?
