### ISSUE TITLE
[BUG] Example missing auxiliary file

### ISSUE THREAD

**Issue by mmmarinho** [dqrobotics/cpp-examples#7]
@juanjqo 
I think that the following example is missing a couple of `.csv` files mentioned in the code. I'm guessing those files are supposed to be on the same folder... Is my understanding correct?

https://github.com/dqrobotics/cpp-examples/blob/8db5d88f68149c77236e60c7e8ef2ed75c1f5064/cmake/vrep_interface_tests/joint_torque_commands/joint_torque_commands.cpp#L142

**Comment by juanjqo** [comment]
@mmmarinho, 
Both files are not supposed to be in the same folder a priori. When the joint_torque_commands.cpp is executed, both .cvs files are created. 

Example:
![ezgif-1-c04be41431](https://user-images.githubusercontent.com/23158313/158247464-945cb68b-d1ef-4d57-a6f9-601d92f91aaf.gif)

**Comment by mmmarinho** [comment]
@juanjqo  Thanks for the explanation!

**Comment by bvadorno** [comment]
Hi @juanjqo, 

Is this information already in the documentation? If not, may you include it?

Thanks,
Bruno

**Comment by juanjqo** [comment]
Hi @bvadorno, 

The information about the CVS files was not clear. I updated the documentation.

Cheers, 

Juancho
