### ISSUE TITLE
[BUG] Json parse error: unexpected end of input

### ISSUE THREAD

**Issue by juanjqo** [dqrobotics/cpp-examples#9]
**Bug description**
- Hi @mmmarinho! The example json11_interface_example.cpp crashes when executed.

**To Reproduce**
- Compile and run the example json11_interface_example.cpp

*Code*

```
json11_interface_example.cpp
```
*Output*
```
13:44:28: Starting /home/juanjqo/Desktop/cpp-examples/cmake/build-json11_interface-Desktop-Debug/json11_interface_example...
terminate called after throwing an instance of 'std::runtime_error'
  what():  Json parse error: unexpected end of input
13:44:28: /home/juanjqo/Desktop/cpp-examples/cmake/build-json11_interface-Desktop-Debug/json11_interface_example crashed.
```

**Expected behavior**
- I expect that the example runs successfully.

**Environment:**
 - OS: Ubuntu 20.04 LTS
 - dqrobotics version: (development version: 20.04.0-0-202203090039-ubuntu20.04.1).

**Comment by mmmarinho** [comment]
@juanjqo 

Thanks for the report. The example is running just fine on Github Actions, so could you try to figure out why it isn't running on your PC? I'm guessing you're running the example from a different folder than you are supposed to run.

Github Actions result:
![image](https://user-images.githubusercontent.com/46012516/158921727-5755b6ec-3738-411c-b2e7-579c13a06c4a.png)

**Comment by juanjqo** [comment]
Hi @mmmarinho, 

You are right. The problem is related to the folder where the example is executed. When I use the terminal (to compile and run), the example works well. But when I use QT Creator, the example crashes because, in my case, the build folder is created outside the folder json11_interface (by default).  

Running on QT Creator:
![crash](https://user-images.githubusercontent.com/23158313/159100064-38987bbd-8c72-406b-9a96-86bc88633a30.gif)

Running from Terminal:
![terminal](https://user-images.githubusercontent.com/23158313/159100810-6a3cb437-b0d9-4830-bb5f-af11662f8758.gif)

Solutions for QT Creator:
The example runs well on QT Creator by modifying the path of the JSON files in [json11_interface_example.cpp](https://github.com/dqrobotics/cpp-examples/blob/master/cmake/json11_interface/json11_interface_example.cpp)

Specifically, lines 34 and 49.

Before:
"../dq_serial_manipulator_dh.json"
"../dq_serial_manipulator_denso.json"

Working:
"../json11_interface/dq_serial_manipulator_dh.json"
"../json11_interface/dq_serial_manipulator_dh.json"

![solution](https://user-images.githubusercontent.com/23158313/159100370-9f0bb147-7104-4f39-8493-45a662dde7d0.gif)

Of course, another solution is to set the build directory inside the json11_interface folder.

I'm going to add this information in the documentation of the example.

Best regards, 

Juancho
